"""Build the Foothills Labs logo set from the house mark.

The mark is FOOTHILLS REFOLDED — two pleated-paper ranges, no plane — from
candidates/candidate-e3-foothills-refolded.svg, and its colourway is BEACON:
teal/rust/orange facets under the line on light grounds, lifted to
slate/orange/apricot on dark ones, pale-teal back range, set off-register
(candidates/mark-foothills-beacon*.svg, all generated by
candidates/generate.py). Colour surfaces (avatars, favicon, touch icon, the
dark and light lockups) embed that construction; the monoline variants
survive for CSS-tinted and single-colour uses. The wordmark is converted to
outlines so the SVGs carry no font dependency.

Requires fontTools, uharfbuzz, and the Archivo variable font:

    npm install @fontsource-variable/archivo
    pip install fonttools brotli uharfbuzz
    python3 build.py [path/to/archivo-latin-wdth-normal.woff2]

Archivo is SIL Open Font Licence 1.1 (Omnibus-Type). Outlines baked into these
files are covered by it; the OFL permits this and does not extend to the rest of
the repository.
"""

import io
import os
import re
import sys

from fontTools.ttLib import TTFont
from fontTools.varLib import instancer
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.pens.boundsPen import BoundsPen
from fontTools.misc.transform import Transform
import uharfbuzz as hb

HERE = os.path.dirname(os.path.abspath(__file__))
# ONE DRAWING ON SCREEN. Every screen surface — hero, header, favicon, touch
# icon, avatars, lockups — carries both ranges. The small cuts differ from the
# full one in STROKE WEIGHT ALONE (x1.65), never in what is drawn.
#
# This reverses an earlier rule that dropped the back range below ~24 px on the
# theory that the rear peaks silt up. Measured on the site at 30 px they do not:
# the back peaks hold their fill and the valleys stay open, they just need the
# line a weight heavier. Shipping a reduced cut meant shipping two logos — a
# hero with two ranges and a header with one — which is what this avoids.
#
# Print was measured before this was adopted, not assumed: the small cut's
# minimum goes 4.6mm -> 5.2mm on typical coated offset and 6.8mm -> 10.3mm
# uncoated (printsize.py). Business-card scale survives, so the retired
# reduced cut is kept only for the record in candidates/.
MARK_SRC = os.path.join(HERE, "candidates", "candidate-e3-foothills-refolded.svg")
COLOUR_SRC = os.path.join(HERE, "candidates", "mark-foothills-beacon.svg")
COLOUR_SRC_DARK = os.path.join(HERE, "candidates",
                               "mark-foothills-beacon-dark.svg")

def _find_font():
    """Archivo from npm, wherever node_modules landed.

    This directory is `assets/logo/` in foundation_lab and `logo/` in the
    split-out brand repo, so node_modules sits either two levels up or one.
    An explicit path as argv[1] wins over both."""
    if len(sys.argv) > 1:
        return sys.argv[1]
    rel = os.path.join("node_modules", "@fontsource-variable", "archivo",
                       "files", "archivo-latin-wdth-normal.woff2")
    for up in ("..", os.path.join("..", "..")):
        candidate = os.path.join(HERE, up, rel)
        if os.path.exists(candidate):
            return candidate
    # Nothing found: report the near miss rather than a bare ENOENT.
    raise SystemExit(
        "Archivo not found. Run `npm install @fontsource-variable/archivo` "
        "at the repository root, or pass the .woff2 path as the first "
        "argument.")


FONT = _find_font()

C = {
    "orange": "#EE8B33",
    "sumi": "#05192B",
    "cream": "#FAEBD3",
    "night": "#05192B",
    "teal": "#31606D",
    "rust": "#6A2A12",
}

TRACKING = 0.004  # em; the lowercase wordmark needs almost none


# --- the mark ---------------------------------------------------------------

def load_mark(path):
    """Path data and its bounding box. Siwalik is polylines, so M/L only."""
    src = open(path).read()
    ds = re.findall(r'd="([^"]+)"', src)
    pts = [(float(x), float(y))
           for d in ds for x, y in re.findall(r"(-?[\d.]+) (-?[\d.]+)", d)]
    xs, ys = [p[0] for p in pts], [p[1] for p in pts]
    return ds, (min(xs), min(ys), max(xs), max(ys))


def reframe(ds, bbox, box, pad, stroke):
    """Fit the mark into a `box` square with `pad` clear space on every side.

    Stroke is scaled with the art so the drawing keeps its weight, and the
    stroke's own half-width is held inside the padding.
    """
    x0, y0, x1, y1 = bbox
    w, h = x1 - x0, y1 - y0
    inner = box - 2 * pad - stroke
    k = inner / max(w, h)
    ox = pad + stroke / 2 + (inner - w * k) / 2
    oy = pad + stroke / 2 + (inner - h * k) / 2
    out = []
    for d in ds:
        def sub(m, k=k, x0=x0, y0=y0, ox=ox, oy=oy):
            x, y = float(m.group(1)), float(m.group(2))
            return f"{round(ox + (x - x0) * k, 2):g} {round(oy + (y - y0) * k, 2):g}"
        out.append(re.sub(r"(-?[\d.]+) (-?[\d.]+)", sub, d))
    return out, k


def mark_svg(ds, box, stroke, colour=None, ground=None, title="Foothills Labs",
             radius=0):
    col = colour or "currentColor"
    body = ""
    if ground:
        r = f' rx="{radius}"' if radius else ""
        # stroke="none" is load-bearing: the rect sits inside the stroked
        # group below, so without it every tile inherits a hairline border
        # in the mark colour — a bug that shipped once already.
        body += (f'<rect width="{box}" height="{box}"{r} fill="{ground}" '
                 f'stroke="none"/>')
    body += "".join(f'<path d="{d}"/>' for d in ds)
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {box} {box}" '
        f'width="{box}" height="{box}" role="img" aria-label="{title}">'
        f'<title>{title}</title>'
        f'<g fill="none" stroke="{col}" stroke-width="{stroke}" '
        f'stroke-linecap="round" stroke-linejoin="round">{body}</g></svg>'
    ).replace(f'stroke-linejoin="round">{"<rect" if ground else ""}',
              f'stroke-linejoin="round">{"<rect" if ground else ""}')


def load_colour_mark(path):
    """Inner markup and bbox of a colourway SVG, for embedding via <g>.

    The bbox regex-parses every coordinate pair; the off-register fills are
    shifted (13, 10) by transform, so the max corner is padded by that, and
    the stroke's half-width (7.5 at source scale) by that again.
    """
    src = open(path).read()
    inner = src[src.index(">", src.index("<svg")) + 1: src.rindex("</svg>")]
    pts = [(float(x), float(y)) for x, y in
           re.findall(r"(-?[\d.]+) (-?[\d.]+)", " ".join(
               re.findall(r'd="([^"]+)"', src)))]
    xs, ys = [p[0] for p in pts], [p[1] for p in pts]
    m = 7.5
    return inner, (min(xs) - m, min(ys) - m, max(xs) + 13 + m, max(ys) + 10 + m)


def colour_group(inner, bbox, box, pad):
    """Fit the embedded colour mark into a box with pad on every side."""
    x0, y0, x1, y1 = bbox
    w, h = x1 - x0, y1 - y0
    k = (box - 2 * pad) / max(w, h)
    tx = pad + ((box - 2 * pad) - w * k) / 2 - x0 * k
    ty = pad + ((box - 2 * pad) - h * k) / 2 - y0 * k
    return (f'<g transform="translate({tx:.2f} {ty:.2f}) scale({k:.4f})">'
            f'{inner}</g>')


def colour_svg(inner, bbox, box, pad, ground=None, radius=0,
               title="Foothills Labs"):
    body = ""
    if ground:
        r = f' rx="{radius}"' if radius else ""
        body += f'<rect width="{box}" height="{box}"{r} fill="{ground}"/>'
    body += colour_group(inner, bbox, box, pad)
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {box} {box}" '
            f'width="{box}" height="{box}" role="img" aria-label="{title}">'
            f'<title>{title}</title>{body}</svg>')


def mark_group(ds, stroke, colour):
    return (f'<g fill="none" stroke="{colour}" stroke-width="{stroke}" '
            f'stroke-linecap="round" stroke-linejoin="round">'
            + "".join(f'<path d="{d}"/>' for d in ds) + "</g>")


# --- the wordmark -----------------------------------------------------------

def static_archivo(wght=800, wdth=125):
    f = TTFont(FONT)
    inst = instancer.instantiateVariableFont(f, {"wght": wght, "wdth": wdth})
    # Drop the woff2 wrapper — harfbuzz reads sfnt, and a compressed face parses
    # as empty, which shapes every character to .notdef.
    inst.flavor = None
    return inst


def shape(font, text, size):
    """Harfbuzz-shaped outline path for `text`, plus its advance width."""
    buf = io.BytesIO()
    font.save(buf)
    face = hb.Face(buf.getvalue())
    hbfont = hb.Font(face)
    upem = face.upem
    hbfont.scale = (upem, upem)

    buf2 = hb.Buffer()
    buf2.add_str(text)
    buf2.guess_segment_properties()
    hb.shape(hbfont, buf2, {"kern": True, "liga": True})

    order = font.getGlyphOrder()
    glyphset = font.getGlyphSet()
    scale = size / upem
    track = TRACKING * upem

    d, x = [], 0.0
    for info, pos in zip(buf2.glyph_infos, buf2.glyph_positions):
        name = order[info.codepoint]
        pen = SVGPathPen(glyphset, ntos=lambda v: f"{round(v, 2):g}")
        t = Transform(scale, 0, 0, -scale, (x + pos.x_offset) * scale, 0)
        glyphset[name].draw(TransformPen(pen, t))
        got = pen.getCommands()
        if got:
            d.append(got)
        x += pos.x_advance + track
    return " ".join(d), (x - track) * scale


def bbox_of(font, text, size):
    order = font.getGlyphOrder()
    glyphset = font.getGlyphSet()
    buf = io.BytesIO()
    font.save(buf)
    face = hb.Face(buf.getvalue())
    hbfont = hb.Font(face)
    upem = face.upem
    hbfont.scale = (upem, upem)
    b2 = hb.Buffer()
    b2.add_str(text)
    b2.guess_segment_properties()
    hb.shape(hbfont, b2, {"kern": True, "liga": True})
    scale = size / upem
    track = TRACKING * upem
    bp = BoundsPen(glyphset)
    x = 0.0
    for info, pos in zip(b2.glyph_infos, b2.glyph_positions):
        name = order[info.codepoint]
        t = Transform(scale, 0, 0, -scale, (x + pos.x_offset) * scale, 0)
        glyphset[name].draw(TransformPen(bp, t))
        x += pos.x_advance + track
    return bp.bounds  # (xMin, yMin, xMax, yMax) in SVG space, y already flipped


# --- outputs ----------------------------------------------------------------

def write(name, content):
    path = os.path.join(HERE, name)
    with open(path, "w") as fh:
        fh.write(content + "\n")
    print(f"  {name:38s} {len(content):>6,} B")


def main():
    BOX, PAD, STROKE = 64, 4, 1.7
    ds_full, bb_full = load_mark(MARK_SRC)

    mark, _ = reframe(ds_full, bb_full, BOX, PAD, STROKE)
    # The small cut: the SAME drawing, reframed at a heavier stroke. Nothing is
    # dropped from it — see the note on MARK_SRC.
    small, _ = reframe(ds_full, bb_full, BOX, PAD, STROKE * 1.65)

    inner_l, cbb_l = load_colour_mark(COLOUR_SRC)
    inner_d, cbb_d = load_colour_mark(COLOUR_SRC_DARK)

    print("marks")
    write("mark.svg", mark_svg(mark, BOX, STROKE))
    write("mark-colour.svg", colour_svg(inner_l, cbb_l, BOX, 4))
    write("mark-colour-dark.svg", colour_svg(inner_d, cbb_d, BOX, 4))
    for tone in ("orange", "sumi", "cream", "teal"):
        write(f"mark-{tone}.svg", mark_svg(mark, BOX, STROKE, C[tone]))
    write("mark-colour-small.svg", colour_svg(inner_l, cbb_l, BOX, 4))
    write("mark-colour-small-dark.svg", colour_svg(inner_d, cbb_d, BOX, 4))
    write("mark-small.svg", mark_svg(small, BOX, STROKE * 1.65))
    for tone in ("orange", "sumi", "cream", "teal"):
        write(f"mark-small-{tone}.svg",
              mark_svg(small, BOX, STROKE * 1.65, C[tone]))

    print("avatars and favicon")
    # Padding is set for a CIRCULAR crop, not a square one: GitHub and
    # Hugging Face both mask org avatars into circles, and the band ends sit
    # near the corners where an inscribed circle cuts. 88 keeps the whole
    # drawing inside that circle with room to spare.
    # Corner radius matches the favicon's ratio (14/64 = 21.875%), so every
    # tiled cut of the mark shares one corner geometry.
    A, APAD, ASTROKE, ARX = 512, 88, 13.3, 112
    av, _ = reframe(ds_full, bb_full, A, APAD, ASTROKE)
    for name, ground, inner, cbb in (("night", C["night"], inner_d, cbb_d),
                                     ("cream", C["cream"], inner_l, cbb_l)):
        write(f"avatar-{name}.svg",
              colour_svg(inner, cbb, A, APAD, ground=ground, radius=ARX))
    write("avatar-orange.svg", mark_svg(av, A, ASTROKE, C["sumi"],
                                              ground=C["orange"],
                                              radius=ARX))
    # A bordered LIGHT tile. The favicon's border only ever existed on the
    # night ground, so anything wanting the mark on paper with the accent
    # rule around it — a personal page, a slide, an app tile — had nothing.
    # Border geometry is the favicon's, scaled: inset 1.8/64 of the box,
    # stroke 3.6/64, inner radius 12.2/64. Padding stays at APAD so the tile
    # is still circle-safe if something masks it.
    BINSET, BSTROKE, BRX = A * 1.8 / 64, A * 3.6 / 64, A * 12.2 / 64
    for name, ground, inner, cbb in (("cream", C["cream"], inner_l, cbb_l),
                                     ("night", C["night"], inner_d, cbb_d)):
        write(f"avatar-{name}-bordered.svg",
              f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {A} {A}" '
              f'width="{A}" height="{A}" role="img" aria-label="Foothills Labs">'
              f'<title>Foothills Labs</title>'
              f'<rect width="{A}" height="{A}" rx="{ARX}" fill="{ground}"/>'
              f'<rect x="{BINSET:.1f}" y="{BINSET:.1f}" '
              f'width="{A - 2 * BINSET:.1f}" height="{A - 2 * BINSET:.1f}" '
              f'rx="{BRX:.1f}" fill="none" stroke="{C["orange"]}" '
              f'stroke-width="{BSTROKE:.1f}"/>'
              + colour_group(inner, cbb, A, APAD) + '</svg>')
    # Favicon: rounded tile with a pronounced lichen border — a sharp square
    # sat awkwardly next to the round tab controls. The FULL drawing, like
    # every other screen surface: the tab is the one place the old reduced cut
    # was hardest to justify, since the touch icon and the OG card beside it
    # were already carrying both ranges. Padding is 9, which is what the full
    # drawing needs to keep its base off the border ring.
    fav_mark = colour_group(inner_d, cbb_d, 64, 9)
    write("favicon.svg",
          '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" '
          'width="64" height="64" role="img" aria-label="Foothills Labs">'
          '<title>Foothills Labs</title>'
          f'<rect width="64" height="64" rx="14" fill="{C["night"]}"/>'
          f'<rect x="1.8" y="1.8" width="60.4" height="60.4" rx="12.2" '
          f'fill="none" stroke="{C["orange"]}" stroke-width="3.6"/>'
          + fav_mark + "</svg>")
    # Apple touch icon: the GROUND stays square — iOS applies its own corner
    # mask, and pre-rounding it leaves dark notches — but the BORDER is
    # pre-rounded to sit just inside iOS's ~22.5% mask radius, or the mask
    # clips its corners mid-line.
    # Same full drawing and framing as the favicon — these two used to differ,
    # which is precisely how the mark drifted into two logos.
    touch_mark = colour_group(inner_d, cbb_d, 64, 9)
    write("touch-icon.svg",
          '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" '
          'width="64" height="64" role="img" aria-label="Foothills Labs">'
          '<title>Foothills Labs</title>'
          f'<rect width="64" height="64" fill="{C["night"]}"/>'
          f'<rect x="1.8" y="1.8" width="60.4" height="60.4" rx="12.6" '
          f'fill="none" stroke="{C["orange"]}" stroke-width="3.6"/>'
          + touch_mark + "</svg>")

    # Lockups. Cap height drives the optical match between mark and wordmark.
    font = static_archivo()
    print("lockups")
    THEMES = (("dark", (inner_d, cbb_d), C["cream"]),
              ("light", (inner_l, cbb_l), C["sumi"]),
              ("mono", C["orange"], C["orange"]))
    for kind, lines, mark_px in (("horizontal", ["foothills labs"], 64.0),
                                 ("compact", ["foothills", "labs"], 78.0)):
        for theme, fg, wordfg in THEMES:
            write(f"lockup-{kind}-{theme}.svg",
                  lockup(font, ds_full, bb_full, lines, fg, wordfg, mark_px))
    for theme, fg, wordfg in THEMES:
        write(f"lockup-vertical-{theme}.svg",
              vertical(font, ds_full, bb_full, ["foothills", "labs"], fg, wordfg))


def lockup(font, ds, bb, lines, mark_colour, word_colour, mark_px=64.0):
    SIZE = 46.0           # em size for the wordmark
    MARK = mark_px        # mark box
    STROKE = 2.35 * (mark_px / 64.0)
    GAP = 22.0
    LEAD = 0.86           # line height, in em, for the stacked cut

    caps = [bbox_of(font, t, SIZE) for t in lines]
    cap_top = min(b[1] for b in caps)
    cap_bot = max(b[3] for b in caps)
    cap_h = cap_bot - cap_top
    widths = []
    paths = []
    for i, t in enumerate(lines):
        d, _ = shape(font, t, SIZE)
        paths.append(d)
        widths.append(caps[i][2] - caps[i][0])

    if len(lines) == 1:
        text_h = cap_h
    else:
        text_h = cap_h + SIZE * LEAD * (len(lines) - 1)

    if isinstance(mark_colour, tuple):
        mgroup = colour_group(mark_colour[0], mark_colour[1], MARK, 0)
    else:
        mgroup = mark_group(reframe(ds, bb, MARK, 0, STROKE)[0], STROKE,
                            mark_colour)
    word_w = max(widths)

    W = MARK + GAP + word_w
    H = max(MARK, text_h)
    mark_y = (H - MARK) / 2
    # Baselines: first line sits so the whole block is vertically centred.
    y0 = (H - text_h) / 2 - cap_top

    body = [f'<g transform="translate(0 {round(mark_y, 2):g})">'
            + mgroup + "</g>"]
    for i, d in enumerate(paths):
        dy = y0 + i * SIZE * LEAD
        body.append(f'<g fill="{word_colour}" transform="translate('
                    f'{round(MARK + GAP - caps[i][0], 2):g} {round(dy, 2):g})">'
                    f'<path d="{d}"/></g>')

    W, H = round(W, 2), round(H, 2)
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W:g} {H:g}" '
        f'width="{W:g}" height="{H:g}" role="img" aria-label="Foothills Labs">'
        f'<title>Foothills Labs</title>{"".join(body)}</svg>'
    )




def vertical(font, ds, bb, lines, mark_colour, word_colour):
    """Mark above, wordmark centred beneath. For README heroes and cards."""
    SIZE = 40.0
    MARK = 96.0
    STROKE = 3.5
    GAP = 26.0
    LEAD = 0.86

    caps = [bbox_of(font, t, SIZE) for t in lines]
    cap_top = min(b[1] for b in caps)
    cap_bot = max(b[3] for b in caps)
    text_h = (cap_bot - cap_top) + SIZE * LEAD * (len(lines) - 1)
    paths = [shape(font, t, SIZE)[0] for t in lines]
    widths = [b[2] - b[0] for b in caps]

    W = max(MARK, max(widths))
    H = MARK + GAP + text_h
    y0 = MARK + GAP - cap_top

    if isinstance(mark_colour, tuple):
        mg = colour_group(mark_colour[0], mark_colour[1], MARK, 0)
    else:
        mg = mark_group(reframe(ds, bb, MARK, 0, STROKE)[0], STROKE,
                        mark_colour)
    body = [f'<g transform="translate({round((W - MARK) / 2, 2):g} 0)">'
            + mg + "</g>"]
    for i, d in enumerate(paths):
        dx = (W - widths[i]) / 2 - caps[i][0]
        dy = y0 + i * SIZE * LEAD
        body.append(f'<g fill="{word_colour}" transform="translate('
                    f'{round(dx, 2):g} {round(dy, 2):g})"><path d="{d}"/></g>')

    W, H = round(W, 2), round(H, 2)
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W:g} {H:g}" '
        f'width="{W:g}" height="{H:g}" role="img" aria-label="Foothills Labs">'
        f'<title>Foothills Labs</title>{"".join(body)}</svg>'
    )

if __name__ == "__main__":
    main()
