"""Generate tokens.json, including the full contrast matrix.

The palette lives here and in tokens.css; docs/brand.md is the prose that
explains it. Change all three together.

    python3 build.py

Contrast is WCAG 2.1 relative luminance. Every pairing the brand sanctions for
text clears AA (4.5:1); the pairs that fail are ground-on-ground combinations
that are never text, plus signal on a light ground, which is the reason for the
"signal is a fill, not an ink" rule.
"""

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))

PALETTE = {
    "signal":  ("#D9F224", "The one hot colour. A fill, never an ink."),
    "ink":     ("#0C1110", "Near-black with a green cast. Primary dark ground; primary text on light."),
    "basalt":  ("#171E1A", "Raised surface on ink. Tiles, table rows, code blocks."),
    "moss":    ("#39441F", "Deep olive. Model cards and editorial panels. A ground, not a second accent."),
    "alpine":  ("#12688F", "Glacier-lake blue. Second ground and the anchor for chart series."),
    "scree":   ("#8C9689", "Grey with a green bias. Secondary text, rules, axis labels."),
    "glacier": ("#9CC7D8", "Pale cyan. Second chart series and recessive detail."),
    "paper":   ("#F2F3EC", "Warm off-white. Light ground; primary text on dark."),
    "white":   ("#FFFFFF", "Surfaces on the light ground."),
}

GROUNDS = ["ink", "basalt", "moss", "alpine", "paper", "white", "signal"]


def _lin(c):
    c /= 255
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4


def luminance(hex_colour):
    h = hex_colour.lstrip("#")
    r, g, b = (int(h[i:i + 2], 16) for i in (0, 2, 4))
    return 0.2126 * _lin(r) + 0.7152 * _lin(g) + 0.0722 * _lin(b)


def contrast(a, b):
    la, lb = luminance(a), luminance(b)
    return round((max(la, lb) + 0.05) / (min(la, lb) + 0.05), 2)


def build():
    tokens = {
        "$schema": "https://design-tokens.github.io/community-group/format/",
        "meta": {
            "name": "Foothills Labs",
            "source": "docs/brand.md",
            "note": "Generated by assets/tokens/build.py. Edit docs/brand.md, then regenerate.",
        },
        "color": {k: {"value": v[0], "comment": v[1]} for k, v in PALETTE.items()},
        "contrast": {},
        "font": {
            "sans": {"value": "Archivo",
                     "comment": "Variable: wght 100-900, wdth 62-125. SIL OFL."},
            "mono": {"value": "JetBrains Mono",
                     "comment": "Apache-2.0. All figures and labels."},
        },
        "role": {
            "display": {"family": "sans", "weight": 800, "width": 125, "case": "upper"},
            "heading": {"family": "sans", "weight": 700, "width": 112, "case": "upper"},
            "body": {"family": "sans", "weight": 400, "width": 100, "case": "sentence"},
            "data": {"family": "mono", "weight": 400, "numeric": "tabular-nums"},
            "label": {"family": "mono", "weight": 700, "case": "upper", "tracking": "0.2em"},
        },
    }

    for fg in PALETTE:
        row = {}
        for bg in GROUNDS:
            if fg == bg:
                continue
            r = contrast(PALETTE[fg][0], PALETTE[bg][0])
            row[bg] = {"ratio": r, "aa_body": r >= 4.5, "aa_large": r >= 3.0}
        tokens["contrast"][fg] = row

    path = os.path.join(HERE, "tokens.json")
    with open(path, "w") as fh:
        json.dump(tokens, fh, indent=2)
        fh.write("\n")
    print(f"wrote {path}")
    return tokens


if __name__ == "__main__":
    build()
